(dp1
S'output'
p2
S"<type 'exceptions.NameError'> global name 'url' is not defined"
p3
sS'layer'
p4
S'/home/rovyas/Documents/web2py/web2py/applications/pluralsight/controllers/blog.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f9c88c73030, file "/home/rovyas/Documents/web2py/web2py/applications/pluralsight/controllers/blog.py", line 3>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/rovyas/Documents/web2py/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/rovyas/Documents/web2py/web2py/applications/pluralsight/controllers/blog.py", line 25, in <module>\n  File "/home/rovyas/Documents/web2py/web2py/gluon/globals.py", line 414, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/rovyas/Documents/web2py/web2py/applications/pluralsight/controllers/blog.py", line 18, in display_form\n    redirect(url(\'thanks\'))\nNameError: global name \'url\' is not defined\n'
p11
s.