(dp1
S'output'
p2
S"<type 'exceptions.TypeError'> sort() got an unexpected keyword argument 'key'"
p3
sS'layer'
p4
S'/home/rovyas/Documents/web2py/web2py/applications/pluralsight/controllers/polarion.py'
p5
sS'code'
p6
S'<code object <module> at 0x7fd79d85d230, file "/home/rovyas/Documents/web2py/web2py/applications/pluralsight/controllers/polarion.py", line 3>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/rovyas/Documents/web2py/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/rovyas/Documents/web2py/web2py/applications/pluralsight/controllers/polarion.py", line 26, in <module>\n  File "/home/rovyas/Documents/web2py/web2py/gluon/globals.py", line 414, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/rovyas/Documents/web2py/web2py/applications/pluralsight/controllers/polarion.py", line 21, in polarion_view\n    rows.sort(key=operator.itemgetter(\'TC_ID\'))\nTypeError: sort() got an unexpected keyword argument \'key\'\n'
p11
s.